server:
  port: 8082
spring:
  application:
    name: email-service-ms
  datasource:
    username: marko
    password: marko
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
  kafka:
    consumer:
      bootstrap-server:
        - localhost:9092
        - localhost:9094
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: product-created-events
      properties:
        spring.json.trusted.packages: "com.app.ed.core.model"

topics:
  consumer:
    products: product-created-events-topic